import { ArrowLeft, ArrowRight, BookOpen, CheckCircle, Flask, Gauge, List, Plus, Robot, SignOut, Sparkle, Trash, WarningCircle, X } from '@phosphor-icons/react';
import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';

type Agent={id:string;name:string;description:string;instructions:string;model:string;status:string;createdAt:string};
type Source={id:string;title:string;type:string;url?:string;status:string;createdAt:string};
type EvalSummary={total:number;completed:number;passed:number;failed:number;errors:number;canceled:number;overallScore:number;passRate:number;dimensions:Record<string,number>;averageLatencyMs:number;totalTokens:number;failureTags:string[]};
type Scenario={id:string;name:string;input:string;expectedBehavior:string;category:string;assertions?:{mustContain?:string[];mustNotContain?:string[];maxLatencyMs?:number;minLength?:number};latest:null|{status:string;score:number|null;reasoning:string|null;latencyMs:number|null}};
type EvalCase={id:string;status:string;score:number|null;passed:boolean|null;response:string|null;reasoning:string|null;latencyMs:number|null;dimensionScores:Record<string,number>|null;deterministicChecks:Array<{id:string;label:string;passed:boolean;detail:string}>|null;strengths:string[]|null;improvements:string[]|null;failureTags:string[]|null;scenario:Scenario};
type EvalBatch={id:string;status:string;promptHash:string;candidateModel:string;supervisorModel:string;summary:EvalSummary|null;promptReview?:{summary:string;recurringStrengths:string[];recurringFailures:string[];adjustments:Array<{priority:string;issue:string;change:string;expectedImpact:string}>;improvedPrompt:string;model:string;totalTokens:number;generatedAt:string}|null;createdAt:string;completedAt?:string|null;cases?:EvalCase[]};
const api=async <T,>(path:string,init?:RequestInit):Promise<T>=>{const headers:Record<string,string>={...(init?.headers as Record<string,string>||{})};if(init?.body)headers['content-type']='application/json';const response=await fetch(`/api${path}`,{...init,credentials:'include',headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message??'Não foi possível concluir a ação.')}return response.status===204?undefined as T:response.json()};
const apiForm=async <T,>(path:string,body:FormData):Promise<T>=>{const response=await fetch(`/api${path}`,{method:'POST',credentials:'include',body});if(!response.ok){const value=await response.json().catch(()=>({}));throw new Error(value.message??'Não foi possível enviar o arquivo.')}return response.json()};
const date=(value:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value));

function Button({children,variant='primary',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'ghost'|'danger'}){return <button className={`button ${variant}`} {...props}>{children}</button>}
function Field({label,helper,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;helper?:string}){return <label className="field"><span>{label}</span><input {...props}/>{helper&&<small>{helper}</small>}</label>}
function Textarea({label,helper,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string;helper?:string}){return <label className="field"><span>{label}</span><textarea {...props}/>{helper&&<small>{helper}</small>}</label>}
function Notice({children,tone='error'}:{children:ReactNode;tone?:'error'|'success'}){return <div className={`notice ${tone}`}>{tone==='error'?<WarningCircle size={18}/>:<CheckCircle size={18}/>}<span>{children}</span></div>}
function Empty({icon,title,body,action}:{icon:ReactNode;title:string;body:string;action?:ReactNode}){return <div className="empty">{icon}<h3>{title}</h3><p>{body}</p>{action}</div>}
function ForgeMark({inverse=false}:{inverse?:boolean}){return <img className="forge-mark" src={inverse?'/brand/forge-mark-inverse.svg':'/brand/forge-mark.svg'} alt=""/>}
function Brand({inverse=false}:{inverse?:boolean}){return <div className="brand"><ForgeMark inverse={inverse}/><span className="brand-copy"><strong>FORGE</strong><small>BY NETOLABS</small></span></div>}

function AuthPage({onAuth}:{onAuth:()=>void}){const [mode,setMode]=useState<'login'|'register'>('login');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(data)});onAuth()}catch(err){setError(err instanceof Error?err.message:'Falha ao entrar')}finally{setBusy(false)}};return <main className="auth-shell"><section className="auth-story"><Brand inverse/><div><p className="overline">Build · Ground · Evaluate</p><h1>Agentes que sustentam resultados.</h1><p>Crie, conecte conhecimento e prove qualidade antes de colocar um agente para trabalhar.</p></div><div className="story-index"><span>01</span><span>Build</span><span>Ground</span><span>Evaluate</span></div></section><section className="auth-panel"><form onSubmit={submit} className="auth-form"><header><h2>{mode==='login'?'Bem-vindo de volta':'Crie seu workspace'}</h2><p>{mode==='login'?'Continue de onde parou.':'Seu primeiro agente começa aqui.'}</p></header>{error&&<Notice>{error}</Notice>}{mode==='register'&&<Field label="Nome" name="name" autoComplete="name" required minLength={2}/>}<Field label="Email" name="email" type="email" autoComplete="email" required/><Field label="Senha" name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={8} helper="Mínimo de 8 caracteres"/><Button disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar conta'}<ArrowRight size={16}/></Button><button type="button" className="text-button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Ainda não tem conta? Criar agora':'Já tem uma conta? Entrar'}</button></form></section></main>}

function Shell({children,user,onLogout}:{children:ReactNode;user:{name:string};onLogout:()=>void}){const loc=useLocation();const nav=[['/','Painel',Gauge],['/agents','Agentes',Robot]] as const;return <div className="app-shell"><aside><Brand/><nav>{nav.map(([to,label,Icon])=><Link key={to} className={loc.pathname===to?'active':''} to={to}><Icon size={18}/>{label}</Link>)}</nav><div className="account"><span>{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>Workspace pessoal</small></div><button aria-label="Sair" onClick={onLogout}><SignOut size={18}/></button></div></aside><section className="main-area">{children}</section></div>}

function Dashboard(){const [agents,setAgents]=useState<Agent[]|null>(null);useEffect(()=>{api<Agent[]>('/agents').then(setAgents)},[]);return <Page title="Painel" subtitle="A visão essencial do seu workspace." action={<Link className="button primary" to="/agents/new"><Plus size={16}/>Novo agente</Link>}>{!agents?<Skeleton/>:<><section className="metrics"><div><span>Agentes</span><strong>{agents.length}</strong><small>configurados</small></div><div><span>Prontos</span><strong>{agents.filter(a=>a.status==='ready').length}</strong><small>para conversar</small></div><div className="metric-accent"><span>Próximo passo</span><strong>{agents.length?'Avaliar':'Criar'}</strong><small>{agents.length?'rode seu primeiro cenário':'comece pelo essencial'}</small></div></section><section className="section-block"><div className="section-title"><h2>Atividade recente</h2><Link to="/agents">Ver agentes <ArrowRight size={14}/></Link></div>{agents.length?<div className="rows">{agents.slice(0,5).map(a=><AgentRow key={a.id} agent={a}/>)}</div>:<Empty icon={<Robot size={26}/>} title="Nenhum agente ainda" body="Crie o primeiro agente e conecte sua base de conhecimento." action={<Link className="button primary" to="/agents/new">Criar agente</Link>}/>}</section></>}</Page>}
function AgentRow({agent,onDelete}:{agent:Agent;onDelete?:(id:string)=>void}){return <div className="agent-row"><Link to={`/agents/${agent.id}`}><span className="agent-glyph"><Robot size={19}/></span><div><strong>{agent.name}</strong><small>{agent.description||'Sem descrição'}</small></div></Link><span className="status">{agent.status}</span><time>{date(agent.createdAt)}</time>{onDelete&&<button className="icon-button danger" aria-label={`Excluir ${agent.name}`} onClick={()=>onDelete(agent.id)}><Trash size={17}/></button>}</div>}
function AgentsPage(){const [agents,setAgents]=useState<Agent[]|null>(null);const [error,setError]=useState('');const load=useCallback(()=>api<Agent[]>('/agents').then(setAgents).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load]);const remove=async(id:string)=>{if(!confirm('Excluir este agente e todos os dados relacionados?'))return;await api(`/agents/${id}`,{method:'DELETE'});load()};return <Page title="Agentes" subtitle="Configure comportamento, conhecimento e qualidade." action={<Link className="button primary" to="/agents/new"><Plus size={16}/>Novo agente</Link>}>{error&&<Notice>{error}</Notice>}{!agents?<Skeleton/>:agents.length?<div className="rows agent-list">{agents.map(a=><AgentRow key={a.id} agent={a} onDelete={remove}/>)}</div>:<Empty icon={<Robot size={28}/>} title="Seu estúdio está vazio" body="Comece com um agente simples. Você poderá evoluir instruções e conhecimento depois." action={<Link className="button primary" to="/agents/new">Criar agente</Link>}/>}</Page>}
function NewAgent(){const nav=useNavigate();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);try{const data=Object.fromEntries(new FormData(e.currentTarget));const agent=await api<Agent>('/agents',{method:'POST',body:JSON.stringify(data)});nav(`/agents/${agent.id}`)}catch(err){setError(err instanceof Error?err.message:'Erro')}finally{setBusy(false)}};return <Page title="Novo agente" subtitle="Defina o papel. O restante pode evoluir com evidência." back><form className="editor" onSubmit={submit}>{error&&<Notice>{error}</Notice>}<div className="form-grid"><Field label="Nome" name="name" required minLength={2} helper="Curto e reconhecível para sua equipe."/><Field label="Modelo" name="model" defaultValue="gemini-2.5-flash" required/><Field label="Descrição" name="description" placeholder="Ex: responde dúvidas do time comercial"/><Textarea label="Instruções" name="instructions" required minLength={20} rows={10} helper="Explique papel, limites, tom e quando admitir que não sabe."/></div><footer><Link className="button ghost" to="/agents">Cancelar</Link><Button disabled={busy}>{busy?'Criando...':'Criar agente'}</Button></footer></form></Page>}

function AgentDetail(){const {id=''}=useParams();const [agent,setAgent]=useState<Agent|null>(null);const [tab,setTab]=useState<'knowledge'|'evals'|'chat'>('knowledge');useEffect(()=>{api<Agent>(`/agents/${id}`).then(setAgent)},[id]);if(!agent)return <Page title="Carregando" subtitle=""><Skeleton/></Page>;return <Page title={agent.name} subtitle={agent.description||'Agente personalizado'} back action={<span className="model-chip">{agent.model}</span>}><div className="tabs"><button className={tab==='knowledge'?'active':''} onClick={()=>setTab('knowledge')}><BookOpen size={17}/>Conhecimento</button><button className={tab==='evals'?'active':''} onClick={()=>setTab('evals')}><Flask size={17}/>Evals</button><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}><Sparkle size={17}/>Testar</button></div>{tab==='knowledge'&&<Knowledge agentId={id}/>} {tab==='evals'&&<Evals agentId={id}/>} {tab==='chat'&&<Chat agentId={id}/>}</Page>}
function Knowledge({agentId}:{agentId:string}){
  const [items,setItems]=useState<Source[]|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [kind,setKind]=useState<'text'|'url'|'file'>('text'); const [busy,setBusy]=useState(false);
  const load=()=>api<Source[]>(`/agents/${agentId}/knowledge`).then(setItems); useEffect(()=>{load()},[agentId]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{if(kind==='file'){const upload=new FormData();const file=f.get('file');if(!(file instanceof File)||!file.size)throw new Error('Selecione um arquivo.');upload.append('file',file);await apiForm(`/agents/${agentId}/knowledge/upload`,upload)}else{const payload=kind==='text'?{type:kind,title:f.get('title'),content:f.get('content')}:{type:kind,title:f.get('title'),url:f.get('url')};await api(`/agents/${agentId}/knowledge`,{method:'POST',body:JSON.stringify(payload)})}setOpen(false);load()}catch(err){setError(err instanceof Error?err.message:'Erro')}finally{setBusy(false)}};
  const remove=async(id:string)=>{await api(`/agents/${agentId}/knowledge/${id}`,{method:'DELETE'});load()};
  return <section className="workspace-panel"><div className="panel-head"><div><h2>Base de conhecimento</h2><p>Documentos, texto e páginas públicas usados para grounding.</p></div><Button onClick={()=>setOpen(true)}><Plus size={16}/>Adicionar</Button></div>{!items?<Skeleton/>:items.length?<div className="source-grid">{items.map(s=><article key={s.id}><div className="source-icon"><BookOpen size={20}/></div><div><strong>{s.title}</strong><small>{s.type==='url'?s.url:s.type==='file'?'Documento processado':'Texto interno'}</small></div><button className="icon-button danger" onClick={()=>remove(s.id)} aria-label="Excluir fonte"><Trash size={16}/></button></article>)}</div>:<Empty icon={<BookOpen size={27}/>} title="Sem fontes conectadas" body="Adicione um documento, texto ou URL pública para reduzir respostas sem base." action={<Button onClick={()=>setOpen(true)}>Adicionar fonte</Button>}/>} {open&&<Modal title="Nova fonte" onClose={()=>setOpen(false)}><form onSubmit={submit} className="modal-form">{error&&<Notice>{error}</Notice>}<label className="field"><span>Tipo</span><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="text">Texto</option><option value="url">URL pública</option><option value="file">Documento</option></select></label>{kind!=='file'&&<Field label="Título" name="title" required/>}{kind==='url'&&<Field label="URL" name="url" type="url" placeholder="https://" required/>}{kind==='text'&&<Textarea label="Conteúdo" name="content" rows={7} required helper="Cole o material que o agente deve consultar."/>}{kind==='file'&&<Field label="Arquivo" name="file" type="file" accept=".pdf,.docx,.txt,.md,.csv" required helper="PDF, DOCX, TXT, Markdown ou CSV. Até 10 MB."/>}<Button disabled={busy}>{busy?'Processando...':'Adicionar fonte'}</Button></form></Modal>}</section>
}
function Evals({agentId}:{agentId:string}){
  const [items,setItems]=useState<Scenario[]|null>(null); const [batches,setBatches]=useState<EvalBatch[]>([]); const [active,setActive]=useState<EvalBatch|null>(null); const [baseline,setBaseline]=useState<EvalBatch|null>(null); const [open,setOpen]=useState(false); const [running,setRunning]=useState(false); const [reviewing,setReviewing]=useState(false); const [error,setError]=useState('');
  const load=async()=>{const [scenarios,runs]=await Promise.all([api<Scenario[]>(`/agents/${agentId}/evals`),api<EvalBatch[]>(`/agents/${agentId}/eval-runs`)]);setItems(scenarios);setBatches(runs);return runs};
  const openBatch=async(id:string)=>{if(!id){setActive(null);return}setActive(await api<EvalBatch>(`/agents/${agentId}/eval-runs/${id}`))};
  useEffect(()=>{void load().then(runs=>{if(!active&&runs[0])void openBatch(runs[0].id)}).catch(e=>setError(e.message))},[agentId]);
  useEffect(()=>{if(!active?.id||['completed','completed_with_errors','canceled'].includes(active.status))return;const timer=setInterval(()=>{void Promise.all([load(),openBatch(active.id)]).catch(e=>setError(e.message))},3000);return()=>clearInterval(timer)},[active?.id,active?.status]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const list=(name:string)=>String(f.get(name)||'').split(',').map(x=>x.trim()).filter(Boolean);const number=(name:string)=>{const value=Number(f.get(name));return Number.isFinite(value)&&value>0?value:undefined};await api(`/agents/${agentId}/evals`,{method:'POST',body:JSON.stringify({name:f.get('name'),category:f.get('category'),input:f.get('input'),expectedBehavior:f.get('expectedBehavior'),assertions:{mustContain:list('mustContain'),mustNotContain:list('mustNotContain'),maxLatencyMs:number('maxLatencyMs'),minLength:number('minLength')}})});setOpen(false);await load()};
  const run=async()=>{setRunning(true);setError('');try{const result=await api<{batchId:string}>(`/agents/${agentId}/evals/run`,{method:'POST',body:'{}'});await openBatch(result.batchId);await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao executar suite')}finally{setRunning(false)}};
  const remove=async(id:string)=>{await api(`/agents/${agentId}/evals/${id}`,{method:'DELETE'});await load()};
  const improve=async()=>{if(!active)return;setReviewing(true);try{const review=await api<NonNullable<EvalBatch['promptReview']>>(`/agents/${agentId}/eval-runs/${active.id}/improve-prompt`,{method:'POST',body:'{}'});setActive({...active,promptReview:review})}catch(e){setError(e instanceof Error?e.message:'Falha na revisão')}finally{setReviewing(false)}};
  const summary=active?.summary;const delta=summary&&baseline?.summary?summary.overallScore-baseline.summary.overallScore:null;const dimensions=['factuality','relevance','completeness','safety','style'];const labels:Record<string,string>={factuality:'Factualidade',relevance:'Relevância',completeness:'Completude',safety:'Segurança',style:'Estilo'};
  return <section className="workspace-panel eval-workspace"><div className="panel-head"><div><h2>Laboratório de evals</h2><p>Suites persistidas, judge independente, checks determinísticos e revisão do prompt.</p></div><div className="actions"><Button variant="ghost" disabled={!items?.length||running} onClick={run}>{running?'Iniciando...':'Rodar suite'}</Button><Button onClick={()=>setOpen(true)}><Plus size={16}/>Novo cenário</Button></div></div>{error&&<Notice>{error}</Notice>}
    {batches.length>0&&<div className="eval-run-toolbar"><label><span>Execução</span><select value={active?.id||''} onChange={e=>void openBatch(e.target.value)}>{batches.map(run=><option value={run.id} key={run.id}>{date(run.createdAt)} · {run.status}</option>)}</select></label><label><span>Comparar com</span><select value={baseline?.id||''} onChange={async e=>setBaseline(e.target.value?await api<EvalBatch>(`/agents/${agentId}/eval-runs/${e.target.value}`):null)}><option value="">Sem baseline</option>{batches.filter(run=>run.id!==active?.id&&run.summary).map(run=><option value={run.id} key={run.id}>{date(run.createdAt)} · {run.summary?.overallScore.toFixed(1)}</option>)}</select></label>{active&&<a className="button ghost" href={`/api/agents/${agentId}/eval-runs/${active.id}.csv`} download>Exportar CSV</a>}</div>}
    {active&&<section className="eval-suite"><header><div><span className={`result ${active.status}`}>{active.status.replaceAll('_',' ')}</span><code>{active.promptHash.slice(0,12)}</code></div><small>{active.candidateModel} avaliado por {active.supervisorModel}</small></header>{summary?<div className="eval-scorecard"><div className="eval-overall"><span>Score geral</span><strong>{summary.overallScore.toFixed(1)}</strong>{delta!==null&&<small className={delta>=0?'positive':'negative'}>{delta>=0?'+':''}{delta.toFixed(1)} vs baseline</small>}<small>{Math.round(summary.passRate*100)}% aprovados</small></div><div className="eval-dimensions">{dimensions.map(key=><div key={key}><span>{labels[key]}</span><strong>{(summary.dimensions[key]||0).toFixed(1)}</strong></div>)}</div><div className="eval-numbers"><div><span>Latência média</span><strong>{Math.round(summary.averageLatencyMs)}ms</strong></div><div><span>Tokens</span><strong>{summary.totalTokens}</strong></div><div><span>Falhas</span><strong>{summary.failed+summary.errors}</strong></div></div></div>:<Skeleton/>}
      {active.cases&&<div className="eval-case-results">{active.cases.map(item=><article key={item.id}><header><div><strong>{item.scenario.name}</strong><small>{item.scenario.category}</small></div><span className={`result ${item.status}`}>{item.score==null?item.status:item.score.toFixed(1)}</span></header><p>{item.scenario.input}</p>{item.reasoning&&<small className="reason">{item.reasoning}</small>}{item.deterministicChecks?.length?<div className="checks">{item.deterministicChecks.map(check=><span key={check.id} className={check.passed?'pass':'fail'}>{check.passed?<CheckCircle size={13}/>:<WarningCircle size={13}/>} {check.label}</span>)}</div>:null}</article>)}</div>}
      {['completed','completed_with_errors'].includes(active.status)&&<div className="prompt-review"><div className="section-title"><div><h2>Revisão do prompt</h2><p>Consolida padrões recorrentes sem otimizar para um único caso.</p></div><Button onClick={improve} disabled={reviewing||!active.cases?.some(item=>['passed','failed'].includes(item.status))}>{reviewing?'Revisando...':active.promptReview?'Revisar novamente':'Melhorar prompt'}</Button></div>{active.promptReview&&<div className="prompt-review-body"><div><strong>Diagnóstico</strong><p>{active.promptReview.summary}</p><div className="review-columns"><section><h3>Preservar</h3>{active.promptReview.recurringStrengths.map(value=><p key={value}>{value}</p>)}</section><section><h3>Corrigir</h3>{active.promptReview.recurringFailures.map(value=><p key={value}>{value}</p>)}</section></div></div><div><strong>Prompt ajustado</strong><textarea readOnly rows={12} value={active.promptReview.improvedPrompt}/></div></div>}</div>}
    </section>}
    <div className="scenario-heading"><div><h3>Cenários</h3><p>Casos controlados que compõem cada suite.</p></div><span>{items?.length||0} ativos</span></div>{!items?<Skeleton/>:items.length?<div className="eval-list">{items.map(s=><article key={s.id}><div className="eval-top"><div><strong>{s.name}</strong><small>{s.category}</small></div>{s.latest?<span className={`result ${s.latest.status}`}>{s.latest.score==null?s.latest.status:s.latest.score.toFixed(1)}</span>:<span className="result neutral">não executado</span>}<button className="icon-button danger" onClick={()=>remove(s.id)} aria-label={`Excluir ${s.name}`}><Trash size={16}/></button></div><p>{s.input}</p><div className="expect"><span>Espera-se</span>{s.expectedBehavior}</div>{s.latest?.reasoning&&<small className="reason">{s.latest.reasoning}</small>}</article>)}</div>:<Empty icon={<Flask size={27}/>} title="Sem cenários" body="Crie casos que representem respostas corretas, limites e falhas críticas." action={<Button onClick={()=>setOpen(true)}>Criar cenário</Button>}/>} {open&&<Modal title="Novo cenário" onClose={()=>setOpen(false)}><form onSubmit={submit} className="modal-form"><Field label="Nome" name="name" required/><Field label="Categoria" name="category" defaultValue="quality" required/><Textarea label="Entrada" name="input" rows={4} required/><Textarea label="Comportamento esperado" name="expectedBehavior" rows={5} required/><Field label="Deve conter" name="mustContain" helper="Termos separados por vírgula."/><Field label="Não deve conter" name="mustNotContain" helper="Termos separados por vírgula. Falha crítica."/><div className="two-fields"><Field label="Latência máxima (ms)" name="maxLatencyMs" type="number" min={1}/><Field label="Tamanho mínimo" name="minLength" type="number" min={1}/></div><Button>Criar cenário</Button></form></Modal>}</section>
}
function Chat({agentId}:{agentId:string}){const [messages,setMessages]=useState<{role:'user'|'agent';text:string}[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const input=new FormData(form).get('message') as string;if(!input.trim())return;setMessages(m=>[...m,{role:'user',text:input}]);form.reset();setBusy(true);try{const result=await api<{response:string}>(`/agents/${agentId}/chat`,{method:'POST',body:JSON.stringify({message:input})});setMessages(m=>[...m,{role:'agent',text:result.response}])}catch(err){setError(err instanceof Error?err.message:'Erro')}finally{setBusy(false)}};return <section className="chat"><div className="messages">{!messages.length&&<Empty icon={<Sparkle size={27}/>} title="Teste em contexto" body="Faça uma pergunta. O agente usará as instruções e a base conectada."/>}{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}{busy&&<div className="message agent typing">Pensando</div>}</div>{error&&<Notice>{error}</Notice>}<form onSubmit={submit}><input name="message" aria-label="Mensagem" placeholder="Pergunte algo ao agente" autoComplete="off"/><Button disabled={busy} aria-label="Enviar"><ArrowRight size={18}/></Button></form></section>}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18}/></button></header>{children}</div></div>}
function Page({title,subtitle,action,back,children}:{title:string;subtitle:string;action?:ReactNode;back?:boolean;children:ReactNode}){return <main className="page"><header className="page-head"><div>{back&&<Link className="back" to="/agents"><ArrowLeft size={15}/>Agentes</Link>}<h1>{title}</h1><p>{subtitle}</p></div>{action}</header>{children}</main>}
function Skeleton(){return <div className="skeleton"><span/><span/><span/></div>}
export function App(){const [state,setState]=useState<'loading'|'guest'|'ready'>('loading');const [user,setUser]=useState<{name:string}|null>(null);const load=()=>api<{user:{name:string}}>('/auth/me').then(r=>{setUser(r.user);setState('ready')}).catch(()=>setState('guest'));useEffect(()=>{load()},[]);if(state==='loading')return <div className="boot"><ForgeMark inverse/></div>;if(state==='guest')return <AuthPage onAuth={load}/>;const logout=async()=>{await api('/auth/logout',{method:'POST'});setState('guest')};return <Shell user={user!} onLogout={logout}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/agents" element={<AgentsPage/>}/><Route path="/agents/new" element={<NewAgent/>}/><Route path="/agents/:id" element={<AgentDetail/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}
