const base = process.env.API_URL ?? 'http://127.0.0.1:4010';
let cookie = '';
const call = async (path, options = {}) => {
  const headers = { cookie, ...options.headers }; if (options.body) headers['content-type'] = 'application/json';
  const response = await fetch(`${base}${path}`, { ...options, headers });
  const setCookie = response.headers.get('set-cookie'); if (setCookie) cookie = setCookie.split(';')[0];
  if (!response.ok) throw new Error(`${options.method ?? 'GET'} ${path}: ${response.status} ${await response.text()}`);
  return response.status === 204 ? null : response.json();
};

const suffix = Date.now().toString(36);
const email = `smoke-${suffix}@example.test`; const password = 'correct-horse-battery';
const registration = await call('/auth/register', { method: 'POST', body: JSON.stringify({ name: 'Smoke User', email, password }) });
if (!registration.user?.id) throw new Error('Registration did not return a user');
const session = await call('/auth/me'); if (session.user?.email !== email) throw new Error('Session cookie was not accepted');
const prompt = await call('/prompts/generate', { method: 'POST', body: JSON.stringify({ name: 'Knowledge Assistant', definition: 'Answer support questions from controlled knowledge and escalate unsupported requests.', guardrails: ['Never invent support policies.'] }) });
if (!prompt.instructions?.includes('# Guardrails') || !prompt.guardrails?.length) throw new Error('Prompt generation did not return a guarded prompt');
const agent = await call('/agents', { method: 'POST', body: JSON.stringify({ name: 'Knowledge Assistant', description: 'Answers from controlled sources', instructions: prompt.instructions, promptDefinition: 'Answer support questions from controlled knowledge.', guardrails: prompt.guardrails, generatedPrompt: true, model: 'gemini-2.5-flash' }) });
const source = await call(`/agents/${agent.id}/knowledge`, { method: 'POST', body: JSON.stringify({ type: 'text', title: 'Smoke knowledge', content: 'The support window is Monday through Friday from 09:00 to 18:00.' }) });
const upload = new FormData(); upload.append('file', new Blob(['Refunds are processed within five business days.'], { type: 'text/plain' }), 'refund-policy.txt');
const uploadResponse = await fetch(`${base}/agents/${agent.id}/knowledge/upload`, { method: 'POST', headers: { cookie }, body: upload }); if (!uploadResponse.ok) throw new Error(`File upload failed: ${uploadResponse.status} ${await uploadResponse.text()}`); const uploaded = await uploadResponse.json();
const waitForSources = async () => { for (let attempt = 0; attempt < 30; attempt += 1) { const rows = await call(`/agents/${agent.id}/knowledge`); if (rows.filter((item) => [source.id, uploaded.id].includes(item.id)).every((item) => item.status === 'ready')) return rows; await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error('Knowledge jobs did not finish'); };
await waitForSources();
const detail = await call(`/agents/${agent.id}/knowledge/${source.id}`); if (!detail.rawText?.includes('support window') || !detail.chunks?.length || !detail.jobs?.some((job) => job.status === 'completed')) throw new Error('Knowledge detail did not expose persisted content and worker history');
await call(`/agents/${agent.id}/knowledge/${source.id}`, { method: 'PATCH', body: JSON.stringify({ active: false }) });
const inactive = await call(`/agents/${agent.id}/knowledge/${source.id}`); if (inactive.active !== false) throw new Error('Knowledge source could not be inactivated');
await call(`/agents/${agent.id}/knowledge/${source.id}`, { method: 'PATCH', body: JSON.stringify({ active: true }) });
await call(`/agents/${agent.id}/knowledge/${source.id}/reprocess`, { method: 'POST', body: '{}' });
await waitForSources();
const generated = await call(`/agents/${agent.id}/evals/generate`, { method: 'POST', body: JSON.stringify({ questions: ['When is support available?'], count: 5 }) });
if (generated.scenarios?.length !== 5 || !generated.scenarios.some((item) => item.generatedBy === 'supervisor')) throw new Error('Eval supervisor did not create scenarios');
const scenario = await call(`/agents/${agent.id}/evals`, { method: 'POST', body: JSON.stringify({ name: 'Support hours', category: 'grounding', input: 'When is support available?', expectedBehavior: 'State Monday through Friday from 09:00 to 18:00.', assertions: { mustContain: ['Monday', '18:00'], mustNotContain: ['24/7'] } }) });
const [agents, sources, scenarios] = await Promise.all([call('/agents'), call(`/agents/${agent.id}/knowledge`), call(`/agents/${agent.id}/evals`)]);
if (!agents.some((item) => item.id === agent.id) || !sources.some((item) => item.id === source.id) || !sources.some((item) => item.id === uploaded.id) || !scenarios.some((item) => item.id === scenario.id)) throw new Error('Created records were not isolated and retrievable');
const overview = await call('/analytics/overview?days=30'); if (overview.totals.requests < 2 || overview.knowledge.ready < 2) throw new Error('Observability overview did not aggregate calls and knowledge');
const modelCalls = await call('/analytics/calls?limit=20'); if (!modelCalls.some((item) => item.kind === 'prompt_generation') || !modelCalls.some((item) => item.kind === 'eval_generation')) throw new Error('Model call ledger is incomplete');
const callDetail = await call(`/analytics/calls/${modelCalls[0].id}`); if (!callDetail.input) throw new Error('Model call detail is unavailable');
const ownerCookie = cookie;
await call('/auth/register', { method: 'POST', body: JSON.stringify({ name: 'Second Tenant', email: `tenant-${suffix}@example.test`, password }) });
const isolatedAgents = await call('/agents'); if (isolatedAgents.some((item) => item.id === agent.id)) throw new Error('Agent leaked across workspaces');
const isolatedCalls = await call('/analytics/calls?limit=20'); if (isolatedCalls.some((item) => modelCalls.some((ownerCall) => ownerCall.id === item.id))) throw new Error('Observability data leaked across workspaces');
cookie = ownerCookie;
await call(`/agents/${agent.id}`, { method: 'DELETE' });
const remaining = await call('/agents'); if (remaining.some((item) => item.id === agent.id)) throw new Error('Agent cascade delete failed');
await call('/auth/logout', { method: 'POST' });
const denied = await fetch(`${base}/agents`, { headers: { cookie } }); if (denied.status !== 401) throw new Error(`Logout did not revoke the browser session: ${denied.status}`);
const login = await call('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); if (login.user?.email !== email) throw new Error('Login failed after logout');
console.log(JSON.stringify({ ok: true, registration: true, login: true, logout: true, tenantIsolation: true, agentCrud: true, promptGeneration: true, knowledgeWorker: true, knowledgeDetail: true, knowledgeActivation: true, knowledgeText: true, knowledgeUpload: true, evalGeneration: true, evalScenario: true, observability: true, pricingLedger: true, cascadeDelete: true }));
