import { ArrowSquareOut, Check, Lightning } from '@phosphor-icons/react';
import { useEffect, useState } from 'react';
import { api } from '../api';
import { Button, Notice, Skeleton } from '../ui';

type Plan = { key: 'solo' | 'studio' | 'scale'; name: string; prices: { brl: number; usd: number }; activeAgentLimit: number; storedAgentLimit: number | null; requestsPerActiveAgent: number; totalIncludedRequests: number; benchlineIncluded: boolean };
type BillingState = { plan: Plan & { key: string }; subscription: null | { status: string; cancelAtPeriodEnd: boolean; currentPeriodEnd?: string | null }; paidAccess: boolean; agents: Array<{ agentId: string | null; trial: { used: number; limit: number }; paid: { used: number; limit: number } }> };

export function Billing() {
  const [plans, setPlans] = useState<Plan[] | null>(null); const [state, setState] = useState<BillingState | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = () => Promise.all([api<{ plans: Plan[] }>('/billing/catalog'), api<BillingState>('/billing/status')]).then(([catalog, status]) => { setPlans(catalog.plans); setState(status); });
  useEffect(() => { void load().catch((reason) => setError(reason.message)); }, []);
  const checkout = async (plan: Plan['key']) => { if (state?.paidAccess) return portal(); setBusy(plan); setError(''); try { const result = await api<{ url: string | null }>('/billing/checkout', { method: 'POST', body: JSON.stringify({ plan, currency: 'brl' }) }); if (!result.url) throw new Error('Checkout indisponível.'); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao abrir checkout'); setBusy(''); } };
  const portal = async () => { setBusy('portal'); try { const result = await api<{ url: string }>('/billing/portal', { method: 'POST', body: '{}' }); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao abrir portal'); setBusy(''); } };
  return <main className="page"><header className="page-head billing-head"><div><p className="eyebrow">Forge / Billing</p><h1>Plano e franquias</h1><p>30 execuções por agente para testar. Depois, cada slot ativo inclui 1.500 requisições por período.</p></div>{state?.subscription && <Button variant="ghost" disabled={busy === 'portal'} onClick={() => void portal()}>Gerenciar no Stripe<ArrowSquareOut size={16}/></Button>}</header>{error && <Notice>{error}</Notice>}
    {!plans || !state ? <Skeleton/> : <><section className="current-plan"><div><span>Plano atual</span><strong>{state.plan.name}</strong><small>{state.subscription?.status ?? '30 execuções gratuitas por agente'}</small></div><div><span>Uso rastreado</span><strong>{state.agents.reduce((sum, item) => sum + item.trial.used + item.paid.used, 0)}</strong><small>requisições consumidas</small></div><div><span>Benchline</span><strong>{state.paidAccess ? 'Incluído' : 'Disponível nos planos'}</strong><small>Evals vinculados por consentimento</small></div></section><section className="pricing-grid">{plans.map((plan) => <article className={state.plan.key === plan.key ? 'pricing-card selected' : 'pricing-card'} key={plan.key}><header><span>{plan.name}</span><div><strong>R$ {plan.prices.brl}</strong><small>/mês</small></div></header><ul><li><Check size={16}/>{plan.activeAgentLimit} {plan.activeAgentLimit === 1 ? 'agente ativo' : 'agentes ativos'}</li><li><Check size={16}/>{plan.totalIncludedRequests.toLocaleString('pt-BR')} requisições/mês</li><li><Check size={16}/>1.500 por agente ativo</li><li><Check size={16}/>Benchline e evals incluídos</li>{plan.storedAgentLimit === null && <li><Check size={16}/>Definições armazenadas sem limite</li>}</ul><Button disabled={busy === plan.key || state.plan.key === plan.key} onClick={() => void checkout(plan.key)}><Lightning size={16}/>{state.plan.key === plan.key ? 'Plano atual' : busy === plan.key ? 'Abrindo...' : state.paidAccess ? 'Alterar no portal' : `Escolher ${plan.name}`}</Button></article>)}</section><p className="pricing-note">Preços são a hipótese comercial inicial. Não há cobrança excedente automática: ao atingir a franquia, o Forge bloqueia novas execuções até a renovação ou mudança de plano.</p></>}
  </main>;
}
