import { ArrowSquareOut, Check, Lightning, WarningCircle } from '@phosphor-icons/react';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../api';
import { Button, Notice, Skeleton } from '../ui';

type Plan = { key: 'solo' | 'studio' | 'scale'; name: string; prices: { brl: number; usd: number }; activeAgentLimit: number; storedAgentLimit: number | null; requestsPerActiveAgent: number; totalIncludedRequests: number; benchlineIncluded: boolean };
type NormalizedBillingState = 'free' | 'checkout_pending' | 'trialing' | 'active' | 'past_due_grace' | 'past_due_blocked' | 'cancel_scheduled' | 'paused' | 'canceled' | 'incomplete' | 'reconciliation_required';
type BillingState = { plan: Plan & { key: string }; subscription: null | { status: string; cancelAtPeriodEnd: boolean; currentPeriodEnd?: string | null; graceUntil?: string | null }; normalizedState: NormalizedBillingState; paidAccess: boolean; portalAvailable: boolean; canManageBilling: boolean; agents: Array<{ agentId: string | null; trial: { used: number; limit: number }; paid: { used: number; limit: number } }> };

export function billingLifecyclePresentation(state: Pick<BillingState, 'normalizedState' | 'subscription' | 'plan'>, locale = 'pt-BR') {
  const date = state.subscription?.currentPeriodEnd ? new Intl.DateTimeFormat(locale, { dateStyle: 'long' }).format(new Date(state.subscription.currentPeriodEnd)) : null;
  const grace = state.subscription?.graceUntil ? new Intl.DateTimeFormat(locale, { dateStyle: 'long' }).format(new Date(state.subscription.graceUntil)) : null;
  if (state.normalizedState === 'checkout_pending') return { tone: 'pending', title: 'Confirmação do Checkout pendente', detail: 'O retorno do Stripe não confirma pagamento. O acesso muda somente após a confirmação segura do webhook.' };
  if (state.normalizedState === 'cancel_scheduled') return { tone: 'pending', title: 'Cancelamento agendado', detail: date ? `Seu acesso pago continua até ${date}.` : 'Seu acesso pago continua até o fim do período atual.' };
  if (state.normalizedState === 'past_due_grace' || state.normalizedState === 'past_due_blocked') return { tone: 'attention', title: 'Pagamento precisa de atenção', detail: grace && state.normalizedState === 'past_due_grace' ? `Atualize o pagamento no Stripe. O período de recuperação vai até ${grace}.` : 'Atualize o pagamento no Stripe para recuperar o acesso pago.' };
  if (state.normalizedState === 'canceled') return { tone: 'neutral', title: 'Assinatura encerrada', detail: 'Seus agentes, conversas e evals continuam preservados. Você pode assinar novamente quando quiser.' };
  if (state.normalizedState === 'active' || state.normalizedState === 'trialing') return { tone: 'paid', title: 'Pagamento confirmado', detail: `${state.plan.name} está ativo.${date ? ` Renova em ${date}.` : ''}` };
  if (state.normalizedState === 'incomplete') return { tone: 'attention', title: 'Pagamento não concluído', detail: 'Conclua ou atualize o pagamento no Stripe antes de usar os recursos do plano.' };
  if (state.normalizedState === 'reconciliation_required') return { tone: 'attention', title: 'Revisão de cobrança necessária', detail: 'O estado local não pôde ser confirmado. Nenhum novo acesso pago será concedido até a reconciliação.' };
  return null;
}

export function Billing() {
  const [plans, setPlans] = useState<Plan[] | null>(null); const [state, setState] = useState<BillingState | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = useCallback(() => Promise.all([api<{ plans: Plan[] }>('/billing/catalog'), api<BillingState>('/billing/status')]).then(([catalog, status]) => { setPlans(catalog.plans); setState(status); }), []);
  useEffect(() => { void load().catch((reason) => setError(reason.message)); }, [load]);
  useEffect(() => {
    if (new URLSearchParams(window.location.search).get('checkout') !== 'success') return;
    let active = true; let attempts = 0;
    const poll = () => { attempts += 1; void load().catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Falha ao atualizar cobrança'); }); if (attempts >= 15) window.clearInterval(interval); };
    const interval = window.setInterval(poll, 2_000);
    poll();
    return () => { active = false; window.clearInterval(interval); };
  }, [load]);
  const portal = async () => { setBusy('portal'); setError(''); try { const result = await api<{ url: string }>('/billing/portal', { method: 'POST', body: '{}' }); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao abrir portal'); setBusy(''); } };
  const checkout = async (plan: Plan['key']) => { if (state?.portalAvailable && !['free', 'canceled'].includes(state.normalizedState)) { await portal(); return; } setBusy(plan); setError(''); try { const result = await api<{ url: string | null }>('/billing/checkout', { method: 'POST', body: JSON.stringify({ plan, currency: 'brl' }) }); if (!result.url) throw new Error('Checkout indisponível.'); window.location.assign(result.url); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao abrir checkout'); setBusy(''); } };
  const lifecycle = state ? billingLifecyclePresentation(state) : null;
  const checkoutReturned = new URLSearchParams(window.location.search).get('checkout') === 'success' && state && ['free', 'checkout_pending'].includes(state.normalizedState);
  return <main className="page"><header className="page-head billing-head"><div><p className="eyebrow">Forge / Billing</p><h1>Plano e franquias</h1><p>30 execuções por agente para testar. Depois, cada slot ativo inclui 1.500 requisições por período.</p></div>{state?.portalAvailable && state.canManageBilling && <Button variant="ghost" disabled={busy === 'portal'} onClick={() => void portal()}>Gerenciar no Stripe<ArrowSquareOut size={16}/></Button>}</header>{error && <Notice>{error}</Notice>}
    {!plans || !state ? <Skeleton/> : <>{checkoutReturned && <section className="billing-return" role="status" aria-live="polite"><WarningCircle size={20}/><div><strong>Confirmando sua assinatura</strong><span>O Checkout retornou. Aguardando a confirmação segura do pagamento antes de liberar o plano.</span></div></section>}{lifecycle && <section className={`billing-lifecycle ${lifecycle.tone}`} role="status" aria-live="polite"><div><strong>{lifecycle.title}</strong><span>{lifecycle.detail}</span></div>{state.portalAvailable && state.canManageBilling && ['past_due_grace', 'past_due_blocked', 'cancel_scheduled', 'active', 'trialing', 'incomplete'].includes(state.normalizedState) && <Button variant="ghost" disabled={busy === 'portal'} onClick={() => void portal()}>{state.normalizedState.startsWith('past_due') || state.normalizedState === 'incomplete' ? 'Atualizar pagamento' : 'Gerenciar assinatura'}<ArrowSquareOut size={16}/></Button>}</section>}<section className="current-plan"><div><span>Plano atual</span><strong>{state.plan.name}</strong><small>{state.normalizedState.replaceAll('_', ' ')}</small></div><div><span>Uso rastreado</span><strong>{state.agents.reduce((sum, item) => sum + item.trial.used + item.paid.used, 0)}</strong><small>requisições consumidas</small></div><div><span>Benchline</span><strong>{state.paidAccess ? 'Incluído' : 'Disponível nos planos'}</strong><small>Evals vinculados por consentimento</small></div></section><section className="pricing-grid">{plans.map((plan) => <article className={state.plan.key === plan.key && state.paidAccess ? 'pricing-card selected' : 'pricing-card'} key={plan.key}><header><span>{plan.name}</span><div><strong>R$ {plan.prices.brl}</strong><small>/mês</small></div></header><ul><li><Check size={16}/>{plan.activeAgentLimit} {plan.activeAgentLimit === 1 ? 'agente ativo' : 'agentes ativos'}</li><li><Check size={16}/>{plan.totalIncludedRequests.toLocaleString('pt-BR')} requisições/mês</li><li><Check size={16}/>1.500 por agente ativo</li><li><Check size={16}/>Benchline e evals incluídos</li>{plan.storedAgentLimit === null && <li><Check size={16}/>Definições armazenadas sem limite</li>}</ul><Button disabled={!state.canManageBilling || busy === plan.key || (state.paidAccess && state.plan.key === plan.key)} onClick={() => void checkout(plan.key)}><Lightning size={16}/>{state.paidAccess && state.plan.key === plan.key ? 'Plano atual' : busy === plan.key ? 'Abrindo...' : state.portalAvailable && !['free', 'canceled'].includes(state.normalizedState) ? 'Gerenciar plano' : `Escolher ${plan.name}`}</Button>{!state.canManageBilling && <small className="billing-permission">Somente o proprietário pode alterar a cobrança.</small>}</article>)}</section><p className="pricing-note">Preços são a hipótese comercial inicial. Não há cobrança excedente automática: ao atingir a franquia, o Forge bloqueia novas execuções até a renovação. Trocas e cancelamento são gerenciados no Portal Stripe, conforme a configuração da conta.</p></>}
  </main>;
}
